import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
import puppeteer from 'puppeteer';
const ROOT = '/Users/jurek/Downloads/Claude/Projects/refract';
const MIME={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.ogg':'audio/ogg','.jpg':'image/jpeg'};
const srv=http.createServer((q,r)=>{let f=path.join(ROOT,q.url.split('?')[0]==='/'?'index.html':q.url.split('?')[0]);
 if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');
 fs.readFile(f,(e,b)=>e?r.writeHead(404).end('404 '+q.url):r.writeHead(200,{'content-type':MIME[path.extname(f)]||'application/octet-stream'}).end(b));});
await new Promise(r=>srv.listen(8199,r));
const b=await puppeteer.launch({headless:'new',executablePath:process.env.C,args:['--enable-unsafe-swiftshader','--use-gl=angle','--mute-audio']});
const p=await b.newPage(); await p.setViewport({width:720,height:694});
p.on('console',m=>console.log('['+m.type()+']',m.text().slice(0,300)));
p.on('pageerror',e=>console.log('[PAGEERROR]',e.message.slice(0,300)));
p.on('requestfailed',r=>console.log('[404/FAIL]',r.url().replace('http://localhost:8199',''),r.failure()?.errorText));
p.on('response',r=>{if(r.status()>=400)console.log('[HTTP '+r.status()+']',r.url().replace('http://localhost:8199',''));});
await p.goto('http://localhost:8199/?capture=1',{waitUntil:'networkidle0',timeout:30000}).catch(e=>console.log('GOTO',e.message));
await new Promise(r=>setTimeout(r,3000));
console.log('REFRACT keys:', await p.evaluate(()=>window.REFRACT?Object.keys(window.REFRACT):'MISSING'));
console.log('readyState:', await p.evaluate(()=>{ if(!window.REFRACT||!window.REFRACT.ready) return 'no ready';
  return Promise.race([window.REFRACT.ready.then(()=>'RESOLVED'), new Promise(r=>setTimeout(()=>r('PENDING'),2000))]);}));
console.log('boot marker:', await p.evaluate(()=>window.__REFRACT_BOOT__||'none'));
await b.close(); srv.close();
